### PR TITLE
Shift "Getting Started" to top and change style

### PR DESCRIPTION
**Pull request by arjunsalyan**
Maybe the "Getting Started" menu could be placed at the top like a primary menu with some modern-styling. I have tried to use colours from the MacPorts logo

Screenshot 2019-04-26 at 12 06 43 AM

### CODE REVIEW

**Comment by mojca** [comment]
@gagarine made the previous suggestions in #13.

I certainly like the changes, but at the same time we should probably also reduce the number of entries in the menu to avoid issues on smaller displays (which calls for changes unrelated to css :), or try to figure out if we could organize the info in a way that would not ask for the second menu, or do it in a different way. Maybe we should set up some brainstorming meeting about design (and structure) improvements?

While waiting for further feedback from other members ...

In #13 we changed the design of the main website, but https://guide.macports.org remained untouched and is now inconsistent with the rest. Since you seem to be in "design mode", would you be willing to check https://github.com/macports/macports-guide and try to make it "consistent" with the main page, or simply improved in whatever way you see fit?

Thanks a lot for this contribution.

@umeshksingla

**Comment by gagarine** [comment]
I like the change but in my opinion, starting from scratch with a super simple website based on https://gohugo.io or another static generator is going to take less time (it should take 1-2 hours max) than trying to fix the actual site. The design is old but mostly the structure and the content is to complex for a "landing page".

It doesn't matter first if the guide is different at the moment. For example https://wagtail.io/ use read the doc for their documentation: http://docs.wagtail.io/en/v2.5/ and this is great.

**Comment by arjunsalyan** [comment]
> I like the change (and it should be merged) but in my opinion, starting from scratch with a super simple website based on https://gohugo.io or another static generator is going to take less time (it should take 1-2 hours max) than trying to fix the actual site.

That sounds good. There are some parts of the website which are not static, like the "Available Ports" page, but it should be replaced by the future web-app. So, if we start from scratch and build both the static site and the web-app based on same design trends- a complete overhaul might go well. And yes, static site shouldn't take much time if we have the content and layout finalised- which as @mojca suggested we could discuss about.

I don't have any experience with Hugo, but I have used Jekyll. [News](https://www.macports.org/news/) could be replaced by blog posts (Jekyll supports them, no idea about Hugo).

**Comment by raimue** [comment]
The News section is already hosted with jekyll and hosted on GitHub. The `/news` URL is transparently proxied to [a site hosted at GitHub](https://github.com/macports/macports.github.io).

**Comment by constantin-p** [comment]
Hi,

I made a [prototype](https://constantin-p.github.io/macports-site/) that includes all 3 sections (macports-www, [macports-guide](https://github.com/macports/macports-guide) & [/news](https://github.com/macports/macports.github.io)) into one central hub. It should solve the design consistency problem, make it easier to maintain/support as everything will be under one roof and written in the same syntax (markdown), and improve the user experience on mobile devices.

There are still a few chapters/sections that need to be added & the functionality of 'Available Ports' needs to be replicated.

**Comment by constantin-p** [comment]
@neverpanic, any thoughts on [this prototype](https://constantin-p.github.io/macports-site/). Sorry to spam the thread, but I don't know in which report should I ask for feedback.

**Comment by mojca** [comment]
@neverpanic: thank you very much for the code review and the merge.

There's only one minor thing left: https://www.macports.org/news/ now looks somewhat strange and probably needs to be fixed soon.

@constantin-p: I find it strange to have documentation in black and the rest in blue, but otherwise the documentation style looks much nicer than it does now. I would be somewhat in favour of consistent usage of asciidoc (as opposed to markdown), and we already have a test conversion to asciidoc ready. I don't know what the support for various tools is.

Available ports are planned to be rewritten as a dynamic page (not php). I would suggest to maybe call a brainstorming meeting about design, perhaps on Saturday one week from now? (But then it would be nice to have access to some "collaboration drawing board" to throw ideas out, and maybe prepare some suggestions upfront :)

**Comment by arjunsalyan** [comment]
> There's only one minor thing left: https://www.macports.org/news/ now looks somewhat strange and probably needs to be fixed soon.

Thank you. I totally missed that news also relies on the same css file. I have create the [pull request](https://github.com/macports/macports.github.io/pull/2).

**Comment by constantin-p** [comment]
@mojca: Is there a protocol I must follow to kick-start a design brainstorming meeting?

Should I open a ticket on [Trac](https://trac.macports.org/) or use the mailing list/irc channel.  Also, what is the ideal place to continue this discussion (I keep spamming this PR thread)?


I wrote down a few ideas about improving [macports.org](https://www.macports.org/) [__here__](https://github.com/constantin-p/macports-site/issues/1).

**Comment by neverpanic** [comment]
> @neverpanic, any thoughts on [this prototype](https://constantin-p.github.io/macports-site/).

I like it, it's much cleaner than what we currently have.

I have my doubts on your attempt to port the guide to a different input format – you should try to avoid copying the contents manually, in case you've done that. We should either style the docbook-generated HTML output using CSS to match or do the conversion to asciidoc(tor).

As for the process, I'd mail to the macports-dev list with an appointment proposal and a planned communication channel and then just see who will respond and join.

**Pull request merged**
