### PR TITLE
Update pastebin links

### PR DESCRIPTION
**Pull request by l2dy**
http://paste.lisp.org/new/macports
>Due to continued abuse, this service has been discontinued

http://pastie.org/
>HTTP/1.1 522 Origin Connection Time-out

### CODE REVIEW

**Comment by ryandesign** [comment]
Why don't we recommend the use of https://paste.macports.org ?

**Comment by l2dy** [comment]
@ryandesign Only MacPorts team members can post to it.

**Comment by ryandesign** [comment]
Any particular reason for that restriction?

**Comment by mojca** [comment]
Probably the same as the above two services were discontinued?

You can easily end up distributing malware or copyright infringements via your bona-fide service. If people are required to login with github, that might to some extent help, not sure how much though.

**Comment by neverpanic** [comment]
We accept pastes up to 16MiB, which is more than most other paste services. Requiring a GitHub account is not really a limitation, since anybody can (probably automated) register new accounts.

Additionally, our pastebin software does provide raw output of the inputs, so people could probably abuse it to host binaries or at least scripts. As much as I'd like running a public pastebin service, I don't think we should pour our manpower into that and just have people use services such as Gist, that already have to deal with spam and abuse.

**Pull request merged**
