### PR TITLE
Modernize a bit the frontend

### PR DESCRIPTION
**Pull request by gagarine**
The website look quit old. I did some very slight change to try to make it look a bit more modern.

It can certainly be improved further without taking to much time, but before I wanted to know if you are open to some change on your website.

screenshot_2019-02-02 the macports project -- home www macports org

My motivation is that I know for webdev look is important and I think macport deserve a bit more attention.

### CODE REVIEW

**Comment by mojca** [comment]
Thanks a lot! We would certainly welcome someone with design experience to do an overhaul of the website. There's nobody in the team that would be particularly skilled with that. This is probably not the only part of the website using this particular (outdated) design (it would be worth checking how https://guide.macports.org works), but I would say that we need to do more than just simple css tweaking anyway, it would make sense to do a major overhaul of how the website is structured to begin with. That's where HB is lightyears ahead of us :( and it probably has a heavy impart on new potential users who immediately get turned away after seeing the webpage itself. If you would be interested, maybe we could have a short brainstorming session together?

Anyway, css tweaking is a small (and important) step towards the final goal. I'm not too skilled in design, so I'm unable to provide a qualified review, but the first impression is nice.

@ryandesign started working on something years ago, but nothing has been deployed so far (and maybe that code no longer even compiles).

**Comment by ryandesign** [comment]
Yes, I still want to modernize our web site, probably removing 95% of the current text or moving it to the Guide. The code of nodejs-based web site rewrite I attempted back in 2012 is no longer relevant, but I will reattempt those design ideas at some point.

**Comment by gagarine** [comment]
I agree that the website need a complete redesign and the front page content need to be simplified. Macports is super simple to use, the website make it look complicated.

Also technically, it need to be responsive and it would be easier to start from scratch that tweaking the current structure.

As nobody seem to have the time or the competences to do that why not take a simple them and use a static website generator like https://gohugo.io/ or https://jekyllrb.com/ ? Then hosting the website on github or gitlab?

**Comment by raimue** [comment]
I fully agree that we should not try to do everything at once. We can easily do incremental steps and replace the main website first and then move on to other parts.

In fact, I would not even mind just throwing the current content of macports.org away. It is overly verbose, redundant to the guide, and a lot of it has not been updated in years. The only useful part that would be dearly missed is the ports database.

Using GitHub Pages might be an option, as we already do that for the [news section](https://github.com/macports/macports.github.io) (using jekyll). Hosting is not a problem in general, we could also put it on our server if it needs anything special.

**Comment by gagarine** [comment]
That's a great news that everybody seem to agree that a new website is needed.

Perhaps we can start a new website from scratch on a new branch? The front page and the blog can certain be on the same repository no? (using jekyll or hugo). And keep the full doc on another repository.

Yet, we can certainly merge this small pull request without taking to much risk. Worst case scenario, we can do a revert.

**Comment by jmroot** [comment]
I can't say the existence of the validation buttons would be among the top 10 problems with our web site in my view, but whatever, they're not really important. I'm also not a fan of Apple's current system font, but I'm probably swimming against the tide there.

**Comment by kencu** [comment]
Are we just waiting for someone to push the button here?

**Comment by mojca** [comment]
We are now waiting for someone to complain and keep improving the interface :)

**Pull request merged**
